version: '3.1'

services:

  mongo:
    image: mongo
    container_name: stackoverflow-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: stack
      MONGO_INITDB_ROOT_PASSWORD: overflow
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: stackoverflow-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: stack
      ME_CONFIG_MONGODB_ADMINPASSWORD: overflow
      ME_CONFIG_MONGODB_URL: mongodb://stack:overflow@stackoverflow-mongodb:27017/